apiVersion: apps/v1
kind: Deployment
metadata:
  name: middleware-deployment
  labels:
    app: middleware
spec:
  replicas: 2
  selector:
    matchLabels:
      app: middleware
  template:
    metadata:
      labels:
        app: middleware
    spec:
      containers:
        - name: middleware
          image: svnnynior/kubernetes-workshop:multiple-apis
          ports:
            - containerPort: 3000
          env:
            - name: SERVICE_NAME
              value: "Middleware Service"
